#############################################################################
#
# Copyright 2020 Thales
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#############################################################################
#
# Original Author: Zbigniew Chamski (zbigniew.chamski@invia.fr)
#
#############################################################################

# Build upon RISC-V Debian "Buster" base image.
FROM cva6thales/cva6thales:base

# Install any additional dependences not present in the base image.
RUN apt install -y python3-pip automake device-tree-compiler

# Create account for the unprivileged user 'riscv' and create the corresponding volume hook.
RUN mkdir -p /home/riscv && useradd -s /bin/bash riscv && chown -R riscv:riscv /home/riscv

# The declaration of the volume must come *AFTER* any modification of its contents.
VOLUME /home/riscv

# Copy the toolchain from the builder.
COPY --from=riscv-debian-buster:toolchain-builder /opt/riscv/toolchain /opt/riscv/toolchain

# Set the user for any subsequent commands to 'riscv' with homedir mounted via the volume.
USER riscv
